# Generated by Django 4.1.5 on 2023-01-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translateProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translateproduct',
            name='active',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='translateproduct',
            name='iva',
            field=models.CharField(max_length=255),
        ),
    ]
