# Generated by Django 4.1.5 on 2023-01-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateProductPostpago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=255, unique=True)),
                ('stok', models.CharField(max_length=255)),
                ('iva', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
            ],
        ),
    ]
